spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_management_system
    username: nika
    password: pass123$
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: nikatsimakuridze199@gmail.com
    password: xbrx gtsg knxz dkyb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081